# Generated by Django 3.2.9 on 2021-11-20 17:29

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='First name', max_length=100)),
                ('last_name', models.CharField(db_column='Last name', max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_column='Phone number', max_length=20)),
                ('url', models.URLField(blank=True, db_column='URL')),
            ],
        ),
        migrations.AddConstraint(
            model_name='addressbook',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique fullname'),
        ),
    ]
