# Generated by Django 3.2.9 on 2021-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='addressbook',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='contact_pics'),
        ),
    ]
