# Generated by Django 3.2.9 on 2021-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211121_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='contact_pics'),
        ),
    ]
