# Generated by Django 3.2.9 on 2021-11-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_addressbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='contact_pics'),
        ),
    ]
