# Generated by Django 3.2.9 on 2021-11-22 15:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_addressbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.get_upload_path),
        ),
    ]
